from typing import Any, Dict, List, Optional
import json
from datetime import datetime
from logging_utils import SAAMLogger

class SAAMTemplate:
    """
    Manages the SAAM data structure based on the SAAM_Evaluation_Extract schema.
    """
    
    def __init__(self):
        self.data = {
            "SAAM_Evaluation_Extract": {
                "metadata": {
                    "paper_id": "",
                    "paper_title": "",
                    "authors": ["AI ArchEval Team"],
                    "year": datetime.now().strftime("%Y"),
                    "venue": "Internal Evaluation",
                    "doi_or_url": "N/A",
                    "extraction_date": datetime.now().strftime("%Y-%m-%d")
                },
                "evaluation_inputs": {
                    "system_context": {
                        "system_name": "",
                        "domain": "Unspecified",
                        "system_description": "",
                        "system_maturity": "Development",
                        "business_goals": ""
                    },
                    "evaluation_setup": {
                        "evaluation_goal": "Assess Modifiability and Functionality",
                        "evaluation_type": "", 
                        "architectures_evaluated": ""
                    },
                    "participants": [
                        { "role": "AI Architect", "count": 1 },
                        { "role": "AI Manager", "count": 1 }
                    ],
                    "architecture_description": {
                        "documentation_level": "Medium",
                        "architecture_styles": [],
                        "architectures": []
                    },
                    "scenario_elicitation": {
                        "elicitation_method": "AI-Driven Brainstorming based on System Context",
                        "scenario_sources": ["Future Needs", "Change Requests"],
                        "scenario_types": ["Use Case", "Change (Growth)", "Change (Exploratory)"]
                    },
                    "evaluation_focus": {
                        "primary_quality_attribute": "Modifiability",
                        "secondary_quality_attributes": ["Functionality"]
                    },
                    "scenario_handling": {
                        "classification_scheme": "Direct vs Indirect",
                        "prioritization_method": "Ranking"
                    }
                },
                "outputs": {
                    "scenarios": [],
                    "scenario_classification": [],
                    "scenario_evaluations": [],
                    "scenario_interactions": [],
                    "scenario_interaction_weights": [],
                    "overall_results": {
                        "architectural_strengths": [],
                        "architectural_weaknesses": [],
                        "modifiability_assessment": ""
                    },
                    "architecture_comparison": [],
                    "recommendations": []
                },
                "extraction_metadata": {
                    "completeness": "Complete",
                    "missing_information": [],
                    "inference_notes": ["Generated by AI Agents"]
                }
            }
        }

    # --- Setters for Evaluation Inputs ---

    def set_system_context(self, name: str, description: str, goals: List[str]):
        ctx = self.data["SAAM_Evaluation_Extract"]["evaluation_inputs"]["system_context"]
        ctx["system_name"] = name
        ctx["system_description"] = description
        ctx["business_goals"] = "; ".join(goals) if isinstance(goals, list) else goals

    def set_architecture_description(self, styles: List[str], architecture_details: Dict):
        desc = self.data["SAAM_Evaluation_Extract"]["evaluation_inputs"]["architecture_description"]
        desc["architecture_styles"] = styles
        # architecture_details should match the "architectures" list item structure
        desc["architectures"] = [architecture_details]

    # --- Setters for Outputs ---

    def add_scenario(self, scenario: Dict):
        """
        Expected format: 
        {"scenario_id": "S-01", "scenario_text": "...", "scenario_type": "...", "stakeholder": "...", "priority": "..."}
        """
        self.data["SAAM_Evaluation_Extract"]["outputs"]["scenarios"].append(scenario)

    def add_classification(self, classification: Dict):
        """
        Expected format:
        {"scenario_id": "S-01", "classification": "Direct | Indirect", "rationale": "..."}
        """
        self.data["SAAM_Evaluation_Extract"]["outputs"]["scenario_classification"].append(classification)

    def add_evaluation(self, evaluation: Dict):
        """
        Expected format:
        {"scenario_id": "...", "architecture_id": "...", "affected_components": [...], "change_description": "...", "issues_identified": [...]}
        """
        self.data["SAAM_Evaluation_Extract"]["outputs"]["scenario_evaluations"].append(evaluation)

    def add_interaction(self, interaction: Dict):
        self.data["SAAM_Evaluation_Extract"]["outputs"]["scenario_interactions"].append(interaction)

    def add_interaction_weighting(self, weighting: Dict):
        self.data["SAAM_Evaluation_Extract"]["outputs"]["scenario_interaction_weights"].append(weighting)

    def set_overall_results(self, strengths: List[str], weaknesses: List[str], assessment: str):
        res = self.data["SAAM_Evaluation_Extract"]["outputs"]["overall_results"]
        res["architectural_strengths"] = strengths
        res["architectural_weaknesses"] = weaknesses
        res["modifiability_assessment"] = assessment

    def add_recommendation(self, recommendation: str):
        self.data["SAAM_Evaluation_Extract"]["outputs"]["recommendations"].append(recommendation)
    def get_template(self) -> Dict:
        return self.data

    def save_to_file(self, filepath: str):
        with open(filepath, 'w') as f:
            json.dump(self.data, f, indent=2)
