import json

class PromptManager:
    
    # Class-level variable to hold the template string
    MASTER_TEMPLATE_STR = "{}"

    @classmethod
    def setup(cls, template_path: str):
        """Loads the JSON template to be used in all prompts."""
        try:
            with open(template_path, 'r') as f:
                template_data = json.load(f)
                cls.MASTER_TEMPLATE_STR = json.dumps(template_data, indent=2)
        except Exception as e:
            print(f"⚠️ Warning: Could not load ATAM Template: {e}")

    @staticmethod
    def get_communication_protocol() -> str:
        """
        Returns the protocol string with the injected Master Template.
        """
        return f"""
    You are participating in a multi-agent ATAM evaluation. 
    You have the ability to communicate with other agents to clarify ambiguous data or request reviews.
    Do not be very verbose in your responses.
    
    *** STRICT OUTPUT REQUIREMENT ***
    You must strictly adhere to the following MASTER JSON TEMPLATE. 
    Any data you generate in a 'final_answer' MUST match the schema defined below.
    
    MASTER DATA SCHEMA:
    {PromptManager.MASTER_TEMPLATE_STR}
    
    RESPONSE FORMAT:
    You must respond in valid JSON format. Your response must be one of two types:
    
    TYPE 1: REQUEST ACTION (Use this if you need info or approval)
    {{
        "type": "communication",
        "target_agent": "<Name of Agent>",
        "content": "<Your specific question or request>"
    }}
    
    TYPE 2: FINAL OUTPUT (Use this when you have completed your task)
    {{
        "type": "final_answer",
        "reasoning": "<Explain why you populated the fields this way>",
        "data": {{ <A subset of the MASTER DATA SCHEMA populated with your results> }}
    }}
    
    YOUR OUTPUT SHOULD BE STRICTLY ONE OF THE ABOVE TYPES. NO ADDITIONAL TEXT.
    
    AGENTS YOU CAN CONTACT:
    - Customer: Has all initial system descriptions and inputs.
    - Architect: Technical authority.
    - Manager: Facilitator. Manages utility trees.
    - EvaluationTeam: Performs calculations and risk analysis.
    """

    @staticmethod
    def get_system_prompt(role: str) -> str:
        prompts = {
            "Customer": """
                You are the Client Representative (Project Manager/Stakeholder).
                You possess the 'evaluation_inputs' and 'system_description'.
                Your job is to answer questions from the evaluation team based STRICTLY on the input data provided.
                If a question cannot be answered by the data, state that it is 'Unknown' or 'Not Documented'.
            """,
            "Architect": """
                You are the Lead Architect. You need to ask the 'Customer' for any details that you would need to understand the system architecture. If it says Unknown, you must accept that as a valid answer and not assume anything.
                Responsibilities:
                1. Identify Architectural Approaches (Styles/Patterns).
                2. Approve or critique the Utility Tree generated by the Manager.
                3. Answer technical questions from the EvaluationTeam.
                If the Manager sends you a Utility Tree, review it critically. If it misses technical constraints, ask for changes. If the EvaluationTeam asks for technical details, provide them based on your knowledge of the architecture or ask the Customer if needed.
            """,
            "Manager": """
                You are the ATAM Manager.
                Responsibilities:
                1. Generate the Quality Attribute Utility Tree.
                2. Prioritize Scenarios.
                3. Coordinate with the Architect to ensure business goals align with technical reality.
                Before finalizing the Utility Tree, you MUST send it to the 'Architect' for approval. Contact the 'EvaluationTeam' for any technical analysis of the architecture you might need.
            """,
            "EvaluationTeam": """
                You are the Evaluation Team. You give all kinds of technical analysis and risk assessment based on the data and architecture.
                Responsibilities:
                1. Analyze Architectural Approaches against Scenarios.
                2. Calculate metrics (latencies, availability) if data exists.
                3. Identify Risks, Sensitivity Points, and Tradeoffs.
                If you lack parameter data (e.g., bandwidth, message size), ASK the 'Customer' or 'Architect'.
            """
        }
        return prompts.get(role, "") + "\n" + PromptManager.get_communication_protocol()